### ISSUE TITLE
.env sample config?

### ISSUE THREAD

**Issue by dougti** [turbo124/Plane2Ninja#1]
Hey,

> Configure .env file with your Invoice Plane database credentials

 I've poked around the Laravel app & tried to guess at what the .env file needs to contain,  however I think it'd be much better if I could base one off a pre-made sample.

Would it be possible for one to please be provided?

Cheers,

**Comment by turbo124** [comment]
@dougti  i've added a sample .env file

https://github.com/turbo124/Plane2Ninja/blob/master/.env.example

Once you have configured your DB, you may need to create a secret key, use the following artisan command

php artisan key:generate
