### ISSUE TITLE
Transform Quotes

### ISSUE THREAD

**Issue by karneaud** [turbo124/Plane2Ninja#2]
Was there any particular reason you left out the "quotes" transformations? I have successfully transferred my invoicePlane data to Invoice Ninja with the exception of the quotes....

**Comment by turbo124** [comment]
No particular reason, I probably just forgot! It won't be much work to bring this over.

**Comment by Braunson** [comment]
Any ETA on this? I'm new to InvoicePlane and InvoiceNinja. I'm actually migrating from Fusion Invoice -> InvoicePlane -> InvoiceNinja lol, only way to migrate my data but quotes are important so I can't move over until this is in place. Have you already started on this @turbo124 yet otherwise I'll take a look.

**Comment by turbo124** [comment]
@Braunson this is on my list, should be completed shortly.

**Comment by karneaud** [comment]
This was quite easy to implement though as invoice ninja uses invoice table for quotes with a column that is set to "is_quote_type" or something of the sort. It was then a matter of replicating the class functions for the invoice migration

**Comment by turbo124** [comment]
@karneaud are you able to PR your changes?

**Comment by karneaud** [comment]
@turbo124 

I should but in the interim https://gist.github.com/karneaud/4eb8f0ba235395bf9ac2b1afb70dec78

**Comment by turbo124** [comment]
@karneaud thanks for this, i'll test the changes and merge. tks!

**Comment by Braunson** [comment]
Oh wow that was quick, awesome. I'll just be waiting on your merge @turbo124. Thanks @karneaud!

**Comment by turbo124** [comment]
#6eaa5df

@Braunson this has been implemented and only lightly tested, please let me know your results!

**Comment by Braunson** [comment]
@turbo124 I ran the updated code, I'm not sure what the download data button is suppose to do it but outputted a bunch of json with no quotes array within it.

**Comment by turbo124** [comment]
Invoice Ninja stores Quotes in the invoice table and uses a boolean is_quote for filtering.

Sounds like your data is ready to import!

**Comment by Braunson** [comment]
Haha oh yeah, apologies!
