### ISSUE TITLE
'App\Models\Payment' not found

### ISSUE THREAD

**Issue by Cronus89** [turbo124/Plane2Ninja#8]
New error after #7 

\`(1/1) FatalThrowableErrorClass 'App\Models\Payment' not found
--
in HasRelationships.php (line 487)
at Model->newRelatedInstance('App\\Models\\Payment')in HasRelationships.php (line 220)
at Model->hasMany('App\\Models\\Payment', 'invoice_id', 'invoice_id')in Invoice.php (line 33)
at Invoice->payments()in Builder.php (line 527)
at Builder->Illuminate\Database\Eloquent\{closure}()
at call_user_func(object(Closure))in Relation.php (line 89)
at Relation::noConstraints(object(Closure))in Builder.php (line 531)
at Builder->getRelation('payments')in Builder.php (line 499)\`

**Comment by turbo124** [comment]
You may need to run:

php artisan clear-compiled

**Comment by Cronus89** [comment]
I re downloaded it all and now i get the below error.

`

(1/1) FatalThrowableErrorType error: Argument 1 passed to App\Plane2Ninja\Transformers\QuoteItemTransformer::transform() must be an instance of App\Models\QuoteItem, instance of App\Models\InvoiceItem given, called in /home/web/htdocs/plane2ninja.tobaccosuper.com/public/app/Plane2Ninja/Ninja/NinjaFactory.php on line 140
--


`
