### ISSUE TITLE
Error when attempting download

### ISSUE THREAD

**Issue by Cronus89** [turbo124/Plane2Ninja#9]
`

(1/1) FatalThrowableErrorType error: Argument 1 passed to App\Plane2Ninja\Transformers\QuoteItemTransformer::transform() must be an instance of App\Models\QuoteItem, instance of App\Models\InvoiceItem given, called in /home/web/htdocs/plane2ninja.****.com/public/app/Plane2Ninja/Ninja/NinjaFactory.php on line 140
--
in QuoteItemTransformer.php (line 16)

`

**Comment by turbo124** [comment]
45de36ac83d37f0ba54a5c206a019420649f79c3 resolves.

**Comment by Cronus89** [comment]
still happens

**Comment by turbo124** [comment]
@Cronus89 Sorry about this - 2010623ab37d5282de3a6909b291df91268c985c - should resolve.

**Comment by Cronus89** [comment]
exports now, it shows the json in browser. im sure its a mimetype thing, not sure what tho.

**Comment by turbo124** [comment]
@Cronus89 great! just cut and paste and save into a file and it is ready for import.
